name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://npm.pkg.github.com
      - name: Install dependecies
        run: npm install
      - name: Version update
        run: npm version prerelease --preid=rc --no-git-tag-version
      - name: git setting
        run: |
          git config --local user.email "nobuhito323@gmail.com"
          git config --local user.name "Nobuhito Iwata"
      - name: Commit files
        run: |
          git add .
          git commit -m "Upgrade version of package.json"
          git push origin HEAD  
      - name: Publish
        run: npm publish --tag=legacy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # # バージョン情報を環境変数として設定
      # - name: set version to env
      #   run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      # # バージョン情報持つタグを付与する
      # - name: add version tag
      #   uses: pkgdeps/git-tag-action@v2
      #   with:
      #     version: ${{ env.VERSION }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     github_repo: ${{ github.repository }}
      #     git_commit_sha: ${{ github.sha }}
      #     git_tag_prefix: "v"