name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://npm.pkg.github.com
      - name: Install
        run: npm install
      - name: Publish
        run: npx can-npm-publish --verbose && npm publish --tag=legacy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}