name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  title-check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pr title
        run: |
          active_apps=$(gh pr list --state=open | cut -f2 | grep -o -E "deploy[1-9]" | cat)
          ARRAY=(item1 item2 item3 item4)
          ARRAY[0]="ITEM1"
          ARRAY[2]="ITEM3"
          echo "ARRAY[0]: ${ARRAY[0]}"
          echo "${active_apps[0]}"
          
          for n in {1..9}
          do
            echo "${active_apps[n]}"
            if [[ "${active_apps}" == *"deploy2"* ]]
            then
              
              exit 1    
            fi
          done
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}