name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  title-check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pr title
        run: |
          active_apps=$(gh pr list --state=open | cut -f2 | cat)
          pr_title=${PR_TITLE} | grep -o -E "deploy[1-9] | cat
          pr_title=`echo "$PR_TITLE" | sed -e "s/^deploy[0-9]/g"`
          echo "${pr_title}"
          # for n in {1..9}
          # do
          #   if [[ “${active_apps}” != ${PR_TITLE} ]] && [[ “${active_apps}” == *“${pr_title}“* ]]
          #   then
          #     echo “Same deploy-devN already exists”
          #     exit 1    
          #   fi
          # done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}