name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  title-check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pr title
        run: |
          active_apps=$(gh pr list --state=open | cut -f2 | cat)
          deployN=$(echo "${PR_TITLE}" | grep -o "deploy[0-9]" | cat)
          for ((i = 0; i < ${#active_apps[@]}; i++)) {
              if [ ${active_apps[i]} != "${PR_TITLE}" ] && [[ ${active_apps[i]} == *${deployN}* ]]
              then
                  echo “${deployN} already exists”
                  exit 1    
              fi
          }
          # for n in "${active_apps[@]}"
          # do
            
          #   if [ "${n}" != "${PR_TITLE}" ]; then
          #     echo "${n}"
          #     echo "${PR_TITLE}"
          #     echo 'ok1'
          #   fi
          #   if [[ ${n} == *${deployN}* ]]; then
          #     echo 'ok2'
          #   fi
          #   if [ "${n}" != "${PR_TITLE}" ] && [[ ${n} == *${deployN}* ]]
          #   then
          #       echo “${deployN} already exists”
          #       exit 1    
          #   fi
          # done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}