name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  title-check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pr title
        run: |
          active_apps=$(gh pr list --state=open | cut -f2 | cat)
          active_apps_array=(`echo $active_apps`)
          deployN=$(echo "${PR_TITLE}" | grep -o "deploy[0-9]" | cat)
          
          for ((i = 0; i < ${#active_apps_array[@]}; i++)) {
              echo "${active_apps_array[i]}"
              if [ "${active_apps_array[i]}" != "${PR_TITLE}" ] && [[ "${active_apps_array[i]}" == *${deployN}* ]]
          then
              echo “${deployN} already exists”
              exit 1    
          fi
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}