name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  title-check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pr title
        run: |
          active_apps=$(gh pr list --state=open | cut -f2 | cat)
          echo "PR_TITLE : ${PR_TITLE}"
          
          for n in {1..9}
          do
            echo "active_apps: ${active_apps[n]}"
            if [[ "${active_apps}" == *"deploy${current_devN}"* ]]
            then
              echo "Same deploy-devN already exists"
              exit 1    
            fi
          done
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}