name: publish my library

env:
  CI: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  title-check:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pr title
        run: |
        num_of_devN=$(gh pr list --state=open | grep ${deploy_devN} | wc -l)
        if [[ $num_of_devN -ge 2 ]]; then
          echo “${deploy_devN} already exists”
          exit 1    
        fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}